## En este ejercicio se realiza operaciones booleanas con separaciones
print (True and True)
print (True and False)
print (False and False)
print ("------------------")
print (True or True)
print (True or False)
print (False or False)
print ("------------------")
print (not True)
print (not False)